name: Parse and Push BALs

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  parse_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run parser
      env:
        ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python parse_and_push.py
        
    - name: Check for new files
      id: check_files
      run: |
        if [ -d "output" ] && [ "$(ls -A output/*.json 2>/dev/null)" ]; then
          echo "new_files=true" >> $GITHUB_OUTPUT
        else
          echo "new_files=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Move files to bals directory
      if: steps.check_files.outputs.new_files == 'true'
      run: |
        mkdir -p bals
        mv output/*.json bals/ || true
        
    - name: Cleanup old files
      if: steps.check_files.outputs.new_files == 'true'
      run: |
        echo "Running cleanup to maintain only latest 7200 files..."
        python cleanup_old_bals.py
        
    - name: Commit and push
      if: steps.check_files.outputs.new_files == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        # Add new files
        git add -f bals/*.json
        # Also stage deletions from cleanup
        git add -A bals/
        # Get counts for commit message  
        NEW_COUNT=$(find output -name "*.json" 2>/dev/null | wc -l || echo "0")
        TOTAL_COUNT=$(find bals -name "*.json" 2>/dev/null | wc -l || echo "0")
        git commit -m "Add BAL blocks and cleanup old files
        
        Added: $NEW_COUNT new blocks
        Total files: $TOTAL_COUNT (max 7200)
        Timestamp: $(date +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push